# Generated by Django 5.2.5 on 2025-08-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order', 'name'], 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_type',
            field=models.CharField(choices=[('appetizer', 'Appetizers'), ('main_course', 'Main Course'), ('soup', 'Soups'), ('dessert', 'Desserts'), ('beverage', 'Beverages'), ('salad', 'Salads'), ('side', 'Sides')], default='main_course', max_length=20),
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
